name: Composer-release

on: [push]

jobs:
  composer-install:
    runs-on: ubuntu-latest

    - name: Install dependencies
      uses: actions/checkout@v3
      uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        php_extensions: gd zip
        version: 2.x
