name: Composer-release
on:
  - push
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: gd zip
          version: 2.x
